package setup

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/RohmanBenyRiyanto/gorun/internal/engine"
	"github.com/RohmanBenyRiyanto/gorun/internal/projectconfig"
)

// runnerTemplate is what gets written to cmd/gorun-runner/main.go. It's
// the project-local half of RunnerPath delegation (see gorun.Config's doc
// comment): the globally-installed gorun binary can't contain a project's
// real seeders, so it execs this instead, which can. Deliberately
// minimal - one obvious TODO, not a framework of its own.
const runnerTemplate = `// Command gorun-runner is what the globally-installed gorun binary hands
// ` + "`gorun seed ...`" + ` off to - it can't carry this project's real seeders
// itself (a YAML file can't express a Go interface implementation), so
// this small entrypoint does: it loads the same .gorun/config.yaml,
// attaches your seeders, and runs the normal gorun command tree. You
// won't normally run this directly.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/RohmanBenyRiyanto/gorun"
)

func main() {
	cfg, err := gorun.LoadConfigFile(".gorun/config.yaml")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// TODO: register your seeders, e.g.:
	// cfg.MySQLSeeders = myapp.MySQLSeeders{}

	cmd := gorun.New(cfg)
	if err := cmd.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`

// configTemplate renders a commented, hand-editable .gorun/config.yaml.
// Building it via text/template rather than yaml.Marshal on a File struct
// keeps the comments and lets each engine's section be omitted entirely
// when it wasn't configured, instead of writing out an empty block.
var configTemplate = template.Must(template.New("config").Funcs(template.FuncMap{
	"quote": strconv.Quote,
}).Parse(`# Generated by ` + "`gorun setup`" + `. Every field here is plain text and
# safe to hand-edit - nothing about this file is generated magic.
{{if .Extends}}
extends: {{.Extends | quote}}
{{end}}
name: {{.Name | quote}}
{{if .Usage}}usage: {{.Usage | quote}}
{{end}}{{if .AppEnv}}app_env: {{.AppEnv | quote}}
{{end}}{{if .MultiDB}}multi_db: true
{{end}}{{if or .MySQL.Configure .PostgreSQL.Configure}}runner_path: "./cmd/gorun-runner"
{{end}}
{{if .MySQL.Configure}}
mysql:
  host: {{.MySQL.Host | quote}}
  port: {{.MySQL.Port | quote}}
  user: {{.MySQL.User | quote}}
  password: {{.MySQL.Password | quote}}
  database_name: {{.MySQL.DatabaseName | quote}}
  parse_time: true
  migration_path: {{.MySQL.MigrationPath | quote}}
  seeder_path: {{.MySQL.SeederPath | quote}}
{{end}}
{{if .PostgreSQL.Configure}}
postgresql:
  host: {{.PostgreSQL.Host | quote}}
  port: {{.PostgreSQL.Port | quote}}
  user: {{.PostgreSQL.User | quote}}
  password: {{.PostgreSQL.Password | quote}}
  database_name: {{.PostgreSQL.DatabaseName | quote}}
  migration_path: {{.PostgreSQL.MigrationPath | quote}}
  seeder_path: {{.PostgreSQL.SeederPath | quote}}
{{end}}
`))

// writeConfig renders a and writes it to <dir>/.gorun/config.yaml. The
// file is created 0600 - it may hold a literal database password if the
// user chose not to use an env reference, so it's kept unreadable to
// other local users by default regardless.
func writeConfig(dir string, a answers) error {
	path := filepath.Join(dir, projectconfig.ConfigRelPath)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
	}

	var buf strings.Builder
	if err := configTemplate.Execute(&buf, a); err != nil {
		return fmt.Errorf("rendering config: %w", err)
	}

	if err := os.WriteFile(path, []byte(buf.String()), 0600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// scaffoldDirs creates database/migrations/<engine> and
// database/seeders/<engine> for every engine a configured, each with a
// .gitkeep so the empty directory is actually tracked by git - it does
// nothing for an engine that wasn't configured, and leaves any directory
// that already exists untouched.
func scaffoldDirs(dir string, a answers) error {
	var engines []string
	if a.MySQL.Configure {
		engines = append(engines, "mysql")
	}
	if a.PostgreSQL.Configure {
		engines = append(engines, "postgresql")
	}

	for _, e := range engines {
		for _, base := range []string{"database/migrations", "database/seeders"} {
			target := filepath.Join(dir, base, e)
			if err := os.MkdirAll(target, 0755); err != nil {
				return fmt.Errorf("creating %s: %w", target, err)
			}
			keep := filepath.Join(target, ".gitkeep")
			if _, err := os.Stat(keep); os.IsNotExist(err) {
				if err := os.WriteFile(keep, nil, 0644); err != nil {
					return fmt.Errorf("writing %s: %w", keep, err)
				}
			}
		}
	}
	return nil
}

// scaffoldRunner writes cmd/gorun-runner/main.go when a configures at
// least one database engine, and then runs `go mod tidy` so that file
// actually compiles without an extra manual step - matching the "as easy
// as possible" bar the rest of setup holds itself to. A failed `go mod
// tidy` (no go.mod yet, no network, ...) is reported as a warning, not a
// setup failure: the config file setup exists to produce is already
// written by the time this runs.
//
// Never overwrites an existing runner - if you've already customized it,
// setup won't know that and shouldn't guess.
func scaffoldRunner(dir string, a answers) error {
	if !a.wantsRunner() {
		return nil
	}

	target := filepath.Join(dir, runnerPath, "main.go")
	if _, err := os.Stat(target); err == nil {
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(target), err)
	}
	if err := os.WriteFile(target, []byte(runnerTemplate), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}

	tidyCmd := exec.Command("go", "mod", "tidy")
	tidyCmd.Dir = dir
	if output, err := tidyCmd.CombinedOutput(); err != nil {
		engine.PrintWarning("Wrote %s, but `go mod tidy` failed - run it yourself before `gorun seed run`:", filepath.Join(runnerPath, "main.go"))
		if len(output) > 0 {
			fmt.Fprintln(os.Stderr, strings.TrimSpace(string(output)))
		}
	}

	return nil
}
